-- Using vim.pack - Neovim's native package manager
-- Plugins are located in ~/.config/nvim/pack/plugins/start/
-- No plugin manager configuration needed - vim.pack loads them automatically!

-- Plugins installed via vim.pack (native):
-- - popup.nvim
-- - plenary.nvim
-- - nvim-autopairs
-- - Comment.nvim
-- - nvim-web-devicons
-- - nvim-tree.lua
-- - lualine.nvim
-- - vim-surround
-- - nvim (catppuccin colorscheme)
-- - dracula.nvim
-- - nvim-cmp (completion)
-- - cmp-buffer, cmp-path, cmp-cmdline, cmp_luasnip, cmp-nvim-lsp, cmp-nvim-lua
-- - LuaSnip (snippet engine)
-- - friendly-snippets
-- - nvim-lspconfig, mason.nvim, mason-lspconfig.nvim, nvim-jdtls
-- - telescope.nvim, telescope-media-files.nvim
-- - nvim-treesitter (with native rainbow bracket support in Nvim 0.12+)
-- - gitsigns.nvim
-- - copilot.vim

-- All plugins are automatically loaded by vim.pack from the start directory
-- Individual plugin configurations are handled in their respective files in lua/user/
